Add notice to README on main
model-checking/kani-github-action pull request #50
Opened 2023-09-27 22:18 UTC by jaisnan

### Description of changes: 

Adds notice about the move to v1, to the README on branch `main`.

2023-09-27 23:58 UTC, celinval commented on README.md
> +        uses: model-checking/kani-github-action@v1.0
```suggestion
        uses: model-checking/kani-github-action@v1
```

2023-09-27 23:58 UTC, celinval commented on README.md
> +Please be aware that version `0.38` will be the final release on the `main` branch before the transition to stable.
```suggestion
Please be aware that version `0.38` will be the final release on the `main` branch before the transition to `v1`.
```

2023-09-28 14:22 UTC, adpaco-aws requested changes
The notice only needs to make clear that from `v1` onwards the Kani version installed by default will be the latest, and `v0.38` will be the last release where the Kani version will match that of the GitHub Action.

2023-09-28 15:00 UTC, adpaco-aws approved these changes

2023-09-28 16:50 UTC, merged